name: Deploy

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List files
        run: ls -la

      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: jaya-currency-conversion
          heroku_email: sereno.desenvolvimento@gmail.com
          usedocker: true
