name: Deploy

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: mvn clean package assembly:single

      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: jaya-currency-conversion
          heroku_email: sereno.desenvolvimento@gmail.com
          usedocker: true
          docker_build_args: |
            JAR_FILE
        env:
          JAR_FILE: jaya-cc-1.0-jar-with-dependencies.jar
